using HW_OOP_13._1;

List<Animal> zoo = new([]);
Omnivorous omnivorous = new Omnivorous(1, "Медведь", 18, 600, 0.067);
zoo.Add(omnivorous);
zoo.Add(new Omnivorous(2, "Ворон", 3, 3.9, 0.462));
zoo.Add(new Omnivorous(3, "свинья", 1, 100, 0.065));
zoo.Add(new Omnivorous(4, "Еж", 1, 0.1, 0.125));
Predator predator = new Predator(5, "Волк", 60, 7, 0.033);
zoo.Add(predator);
zoo.Add(new Predator(6, "Скунс", 2, 5.3, 0.038));
zoo.Add(new Predator(7, "Лиса", 7, 7, 0.143));
zoo.Add(new Predator(8, "Выдра", 3, 12, 0.083));
zoo.Add(new Predator(9, "Норка", 6, 0.2, 0.111));
Herbivore herbivore = new Herbivore(10, "Корова", 10, 450, 0.031);
zoo.Add(herbivore);
zoo.Add(new Herbivore(11, "Лошадь", 550, 5, 0.033));
zoo.Add(new Herbivore(12, "Коза", 12, 50, 0.06));
zoo.Add(new Herbivore(12, "Аист", 7, 7, 0.143));        //Для проверки сортировки по имени
zoo.Add(new Herbivore(13, "Кенгуру", 47, 9, 0.064));
zoo.Add(new Herbivore(14, "Жираф", 10, 800, 0.088));
zoo.Add(new Herbivore(15, "Слон", 18, 5000, 0.06));
ListChanges.PrintList(zoo);
ListChanges.PrintCountName(zoo, 5);
ListChanges.PrintLastId(zoo, 3);
List<Animal> zooNew = new List<Animal>(zoo);
ListChanges.ListSortFoodQuantity(zoo);
ListChanges.PrintList(zoo);
ListChanges.PrintList(zooNew);
ListChanges.PrintCountName(zooNew, 5);
ListChanges.PrintLastId(zooNew, 3);
ListChanges.SaveFile(zoo, "animal1.txt");
ListChanges.SaveFile(zooNew, "animal2.txt");
zoo.Clear();
zooNew.Clear();
ListChanges.PrintList(zoo);
ListChanges.PrintList(zooNew);
ListChanges.ReadFile(zoo, "animal1.txt");
ListChanges.PrintList(zoo);
ListChanges.ReadFile(zooNew, "animal2.txt");
ListChanges.PrintList(zooNew);
