using HomeWork33;
Operations operations = new Operations();
operations.AddString();
operations.Print();
//operations.RemoveAtIndex();
//operations.Print();
operations.RemoveAtIndex();
operations.Print();
Console.Write("Введите название запись для поиска:");
string name = Console.ReadLine()!;
operations.FindList(name);
operations.SortList();
operations.Print();
Console.Write("Введите название запись для поиска:");
name = Console.ReadLine()!;
operations.FindAllValues(name);
operations.Clear();
operations.Print();