using HW_OOP_13;
List<Animal> zoo = new List<Animal>();
Omnivorous omnivorous = new Omnivorous(1, "Медведь", 600, 18, 0.067);
zoo.Add(omnivorous);
zoo.Add(new Omnivorous(2, "Ворон", 3.9, 3, 0.462));
zoo.Add(new Omnivorous(3, "свинья", 100, 1, 0.065));
zoo.Add(new Omnivorous(4, "Еж", 0.1, 1, 0.125));
Predator predator = new Predator(5, "Волк", 60, 7, 0.033);
zoo.Add(predator);
zoo.Add(new Predator(6, "Скунс", 5.3, 2, 0.038));
zoo.Add(new Predator(7, "Лиса", 7, 7, 0.143));
zoo.Add(new Predator(8, "Выдра", 12, 3, 0.083));
zoo.Add(new Predator(9, "Норка", 0.2, 6, 0.111));
Herbivore herbivore = new Herbivore(10, "Корова", 450, 10, 0.031);
zoo.Add(herbivore);
zoo.Add(new Herbivore(11, "Лошадь", 550, 5, 0.033));
zoo.Add(new Herbivore(12, "Коза", 50, 12, 0.06));
zoo.Add(new Herbivore(12, "Аист", 7, 7, 0.143));        //Для проверки сортировки по имени
zoo.Add(new Herbivore(13, "Кенгуру", 47, 9, 0.064));
zoo.Add(new Herbivore(14, "Жираф", 800, 10, 0.088));
zoo.Add(new Herbivore(15, "Слон", 5000, 18, 0.06));
ListChanges.PrintList(zoo);
ListChanges.PrintCountName(zoo, 5);
ListChanges.PrintLastId(zoo, 3);
List<Animal> zooNew = new List<Animal>(zoo);
ListChanges.ListSortFoodQuantity(zooNew);
ListChanges.PrintList(zooNew);
ListChanges.PrintCountName(zooNew, 5);
ListChanges.PrintLastId(zooNew, 3);
ListChanges.SaveFile(zoo, "animal1.txt");
ListChanges.SaveFile(zooNew, "animal2.txt");
zoo.Clear();
zooNew.Clear();
ListChanges.PrintList(zoo);
ListChanges.PrintList(zooNew);
ListChanges.ReadFile(zoo, "animal1.txt");
ListChanges.PrintList(zoo);
ListChanges.ReadFile(zooNew, "animal2.txt");
ListChanges.PrintList(zooNew);